In [25]:
import numpy as np
# Creating a single dimensional array
n1=np.array([10,20,30,40,50])
n1

array([10, 20, 30, 40, 50])

In [26]:
type(n1)

numpy.ndarray

In [27]:
# Multi_dimensional array
n2=np.array([[10,20,30],[40,50,60]])
n2

array([[10, 20, 30],
       [40, 50, 60]])

In [28]:
type(n2)

numpy.ndarray

In [29]:
# Initializing Numpy array with Zeros
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [30]:
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
# creating ones array
n1=np.ones((4,4))
n1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
# Initializing Numpy array with same number
import numpy as np
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [33]:
n1=np.full((5,5),20)
n1

array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [34]:
# np.full
n3=np.full((4,8),5)
n3

array([[5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5]])

In [35]:
# Initializing Numpy array within a range
import numpy as np
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
n1=np.arange(10,50,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [37]:
n1=np.arange(20,50,10)
n1

array([20, 30, 40])

In [38]:
n2=np.arange(100,200,10)
n2

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [39]:
n2=np.arange(100,200)
n2

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [40]:
import numpy as np
# Initilizing numpy array with random numbers
n1=np.random.randint(1,100,20)
n1

array([62, 27, 63, 68, 14, 27, 92, 44, 46, 74, 71, 82, 39, 40, 73, 90, 10,
        1, 12, 31], dtype=int32)

In [41]:
n1=np.random.randint(50,1000,50)
n1

array([394, 474, 353, 294, 350, 929, 662, 680, 419, 956, 851, 215, 406,
       624, 974, 720, 858, 923, 816, 360, 691, 497, 153, 392, 913, 316,
        75, 408, 222,  91, 690, 241, 706, 411, 986, 841, 686, 854, 172,
       707, 258, 114, 347, 202, 932, 388, 733, 499, 881, 218], dtype=int32)