In [3]:
# Numpy array mathematics
# Addition of Numpy Arrays
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])
np.sum([n1,n2])

np.int64(100)

In [4]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [5]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [6]:
# Basic Addition
# Basic Multiplication
# Basic Subtraction
# Basic Division
import numpy as np
n1=np.array([10,20,30,40])
n1=n1+1
n1

array([11, 21, 31, 41])

In [8]:
# Basic Multiplication 
n1=np.array([10,20,30])
n1=n1*2
n1

array([20, 40, 60])

In [9]:
# Basic subtraction
n1=np.array([10,20,30])
n1=n1-1
n1

array([ 9, 19, 29])

In [10]:
# Basic division
n1=np.array([10,20,30])
n1=n1/2
n1

array([ 5., 10., 15.])

In [11]:
# MEAN
# STANDARD DEVIATION
# MEDIAN
import numpy as np
n1=np.array([10,20,30,40])
np.mean(n1)

np.float64(25.0)

In [12]:
# median
import numpy as np
n1=np.array([11,44,5,96,67,85])
np.median

<function median at 0x000001193D09A970>

In [13]:
# standard deviation
import numpy as np
n1=np.array([1,5,3,100,4,48])
np.std(n1)

np.float64(36.59424666377065)

In [14]:
# Numpy matrix Multiplication
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
n1[0]


array([1, 2, 3])

In [19]:
n1[1]

array([4, 5, 6])

In [20]:
n1[2]

array([7, 8, 9])

In [21]:
np.transpose(n1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])