In [7]:
import numpy as np
# Checking the shape of the Numpy Array
n1=np.array([[1,2,3,4],[5,6,7,8]])
n1
n1.shape

(2, 4)

In [9]:
n6=np.array([[10,20,30],[40,50,60]])
n6

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
n6.shape

(2, 3)

In [11]:
# changing the shape of the array
n6.shape=(3,2)
n6

array([[10, 20],
       [30, 40],
       [50, 60]])

In [13]:
# joining the numpy arrays
# 1.vstack()
# 2.hstack()
# 3.column_stack()
import numpy as np
# 1 Vstack()
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [14]:
# hstack()
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [15]:
# column_stack()
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [17]:
# Numpy intersection and difference
import numpy as np
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
np.intersect1d(n1,n2)

array([50, 60])

In [18]:
# Numpy difference
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [19]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
np.setdiff1d(n2,n1)

array([70, 80, 90])